- name: Download k3s installer
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: 0755

- name: Install k3s
  shell: K3S_VERSION={{ k3s_version }} sh /tmp/install_k3s.sh
  args:
    creates: /usr/local/bin/k3s

- name: Link kubeconfig for ec2-user
  file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ec2-user/.kube/config
    owner: ec2-user
    group: ec2-user
    mode: 0600
    force: true
