apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  namespace: devopsproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: 22i1024/notification_service:latest
          ports:
            - containerPort: 5003
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: RABBITMQ_QUEUE
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: RABBITMQ_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
  namespace: devopsproject

spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
