apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-deployment
  namespace: devopsproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: 22i1024/booking_service:latest
          ports:
            - containerPort: 5002
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: POSTGRES_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: POSTGRES_PORT
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: PAYMENT_SERVICE_URL
            - name: EVENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: EVENT_SERVICE_URL
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: RABBITMQ_QUEUE
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: RABBITMQ_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-service
  namespace: devopsproject

spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
