apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: devopsproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 22i1024/user_service:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: POSTGRES_HOST
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-booking-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: DB_NAME
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: event-booking-config
                  key: POSTGRES_PORT


---

apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: devopsproject
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

