apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: onlineeventbookingmuhammadshaifimran
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
