---
- name: Create or update Argo CD Application
  hosts: app_servers
  become: true
  gather_facts: false

  tasks:
    - name: Apply Argo CD Application manifest
      shell: kubectl apply -f /home/ec2-user/DevOps-Project/CS4067-Assignment-02-i221024-MuhammadShaifImran/kubernetes/argocd-app.yaml --kubeconfig=/home/ec2-user/.kube/config
