- name: Install ArgoCD CLI
  get_url:
    url: https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-amd64
    dest: /usr/local/bin/argocd
    mode: 0755

- name: Deploy ArgoCD manifests
  shell: |
    kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml
