name: 'Setup ArgoCD via Ansible'

on:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
      - '.github/workflows/setup-argocd.yml'

jobs:
  install-argocd:
    runs-on: ubuntu-latest
    name: Install Argo CD

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install --update


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run install-argocd.yml
        run: |
          ansible-playbook ansible/install-argocd.yaml
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
